---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# worldle

<!-- badges: start -->
<!-- badges: end -->

The goal of worldle is to be able to play a game of guessing a country based on its shape.

## Installation

You can install the development version of worldle like so:

``` r
remotes::install_github("Stat585-at-ISU/worldle")
```

## Example

How do you play?

```{r example}
library(worldle)
## basic example code
# play_wordle() # that function doesn't exist yet
```

Get the shapefile of a country:
```{r eval=FALSE}
url <- "https://geodata.ucdavis.edu/gadm/gadm4.0/shp/gadm40_AUT_shp.zip"
austria <- get_shapes(url)
austria <- thin(austria, 0.001)
```

Now plot the country: 
```{r}
library(ggplot2)
library(dplyr)

austria %>% ggplot() + geom_sf() + theme_void()
```

Would you have guessed that this is Austria?
